### ISSUE TITLE
[Bug]  fix backend Swagger 

### ISSUE THREAD

**Issue by wangwang-zhang** [au-heartbeat/Heartbeat#346]
### Version

latest

### Summary

for new app backend, the swagger is missing,  we need to config Swagger to automatically generate API documentation.

### Steps to Reproduce

the backend service can run successfully for now, but missing swagger

### Current Behavior

backend service without swagger

### Expected Behavior

automatically generate API documentation when start up backend server.

### Environment

```markdown
- OS:
- Browser:
```

**Comment by guzhongren** [comment]
Go Go Go

**Comment by allenzph** [comment]
Which version of swagger wants to be applied? 2.x or 3.x?

**Comment by guzhongren** [comment]
yes, 3.x
