### ISSUE TITLE
[Bug] verified 应该置灰，不应该是可点击的

### ISSUE THREAD

**Issue by sjmyuan** [au-heartbeat/Heartbeat#689]
### Version

1.1.1

### Summary

![WeChatWorkScreenshot_15b9eb1b-c10e-48ae-9d72-544f73f9a23c](https://github.com/au-heartbeat/Heartbeat/assets/17628688/22148aec-73a0-4d66-ad44-3e07fc280b27)
verified 应该置灰，不应该是可点击的

### Steps to Reproduce

1. 输入project信息
2. 点击verify

### Current Behavior

verify 成功后仍然可以点击verified

### Expected Behavior

verified按钮置灰或不再显示

### Environment

```markdown
- OS:
- Browser:
```

**Comment by jyangTWer** [comment]
Hi @sjmyuan
感谢反馈，问题收到并可以复现。
已建卡：[ADM-584](https://dorametrics.atlassian.net/browse/ADM-584)， 等待优先级确认。

**Comment by davidwangcn9** [comment]
Solved within v1.1.3
