### ISSUE TITLE
[Feature] project和column配置的save按钮功能不清晰

### ISSUE THREAD

**Issue by sjmyuan** [au-heartbeat/Heartbeat#690]
### Summary - What problem does this feature solve?

project和column配置需要save两次，能不能一次，而且可以让用户选择save到browser或本地。 或者默认save到browser，可以导出。 一般不会频繁切换project

### Expectations

只需要有一个save按钮即可

**Comment by Yufan0226** [comment]
Hi @sjmyuan, 
1. 由于配置信息属于敏感信息，不便于保存至浏览器。
2. 在config、metrics、report页面分别设置save button，config页面只保存config页面的配置信息，metrics和report页面保存的是config页面及metrics页面的配置信息。
