### ISSUE TITLE
[Feature] 用户流程建议

### ISSUE THREAD

**Issue by sjmyuan** [au-heartbeat/Heartbeat#692]
### Summary - What problem does this feature solve?

现在使用导入，导出配置太麻烦，我实际使用中不会频繁修改配置，希望能够将配置保存在浏览器，我需要导出再手动导出。

现在每次使用都需要走三步，其实前两步对外完全是浪费时间，我需要的只是修改迭代时间查看数据。

### Expectations

现在使用导入，导出配置太麻烦，我实际使用中不会频繁修改配置，希望能够将配置保存在浏览器，我需要导出再手动导出。

现在每次使用都需要走三步，其实前两步对外完全是浪费时间，我需要的只是修改迭代时间查看数据。

**Comment by jyangTWer** [comment]
Hi @sjmyuan
感谢你的建议，我们已经收到并理解了你的期望
这里先建了一张spike卡用作追踪：[ADM-586](https://dorametrics.atlassian.net/browse/ADM-586), 除了技术实现上的spike之外，我们可能也会考虑到安全风险，有进展再更新。
Thanks

**Comment by Yufan0226** [comment]
Hi,@sjmyuan
考虑到安全风险问题：项目的配置信息属于Confidential information，所以无法将配置保存在浏览器。
对于用户流程的建议我们可以在明日下午的confirm会议上做具体讨论。
感谢你的建议。
