### ISSUE TITLE
[Bug] Don't need to verify board again if I didn't change board information

### ISSUE THREAD

**Issue by sjmyuan** [au-heartbeat/Heartbeat#693]
### Version

1.1.1

### Summary

Don't need to verify board again if I didn't change board information

### Steps to Reproduce

1. verify the board
2. change the collection date

### Current Behavior

I need to verify board again

### Expected Behavior

don't need to verify board if I didn't change anything

### Environment

```markdown
- OS:
- Browser:
```

**Comment by jyangTWer** [comment]
Tracked in [ADM-612](https://dorametrics.atlassian.net/browse/ADM-612)

**Comment by guzhongren** [comment]
Hey,
There is no more conversation, so we close it, and reopen it if you still have Q
