### ISSUE TITLE
[Bug] 404 not found error shows in generate report stage

### ISSUE THREAD

**Issue by mlanyxi** [au-heartbeat/Heartbeat#740]
### What browsers are you seeing the problem on?

Chrome

### Pages

Report

### Tools

Board

### Summary

I want to generate the metrics report, but it shows 404 error.

### Steps to Reproduce

1. successfully fill in the configuration step 
2. successfully fill in the metrics settings 
3. press next button
4. loading page and show 404 not found

### Current Behavior

![Screenshot 2023-11-23 at 5 41 58 pm](https://github.com/au-heartbeat/Heartbeat/assets/140470071/582641a7-afe7-45ce-87ff-c1f6c7f5c885)

### Expected Behavior

Generate report successfully

**Comment by davidwangcn9** [comment]
Hi @mlanyxi ， could you help to verify if your API token got enough permission? For example, if your github token could read all the repos?

**Comment by Yufan0226** [comment]
Hi, @mlanyxi, we wonder that your issue occurred in which version, actually our latest version  in version 1.1.4, please try agin, weather the error still exist, please @ me and let me know, Thanks.

**Comment by guzhongren** [comment]
Hey, 
There is no more conversation, so we close it, and reopen it if you still have Q
