### ISSUE TITLE
frontend-code-standard

### ISSUE THREAD

**Issue by LanxWang** [au-heartbeat/HeartBeat#98]
## 目录

1. 文件目录
2. 编码规范

## 1. frontend project 文件目录如下所示：
```
├── __tests__
│   └── src
├── e2e
│   └── app.test.ts
├── index.html
├── jest.config.json
├── package.json
├── playwright-report
│   └── index.html
├── playwright.config.ts
├── public
│   └── vite.svg
├── src
│   ├── App.css
│   ├── App.tsx
│   ├── assets
│   ├── components
│   ├── config
│   ├── constants
│   ├── hooks
│   ├── main.tsx
│   ├── pages
│   ├── router.tsx
│   ├── service
│   ├── store
│   ├── utils
│   └── vite-env.d.ts
├── tsconfig.json
├── tsconfig.node.json
├── vite.config.ts
└── yarn.lock
```

### 2.1 代码风格和代码质量检查
项目已经配置Eslint, prettier, editorconfig, 并且在每次commit前会进行格式检查。 

### 2.2 关于注释
尽量不写不必要注释，如需写注释，按照约定俗成规范写即可。

### 3.1 HTML
    * 标签内属性在前，事件在后
      ```html
      <div id="testId" onclick = "test()"></div>
      ```

### 3.2 CSS
  * 使用  Sass
    * 命名
      * 禁用**hanyupinyin(汉语拼音)** (约定俗成的除外，如: youku , baidu , alibaba), 尽量使用专业英语
      * 驼峰式命名
      * 参数化命名，如黑色主题和白色主题，应写为 theme-black 和 theme-white

    * 内联外联
      * 尽可能地把样式分为外联样式，通过 class 引入，且有组织的分为全局样式和局部样式文件
    * 响应式页布局
      > **不要出现一个页面有两套 CSS 样式**
      * **在布局块状元素时，要么不设置高宽由内部元素自动撑开，要么定义 100%**
      * **flexbox 布局**（首选，注意各浏览器兼容性处理）
      * grid 布局
      * bootstrap12 栅格布局
      * 百分比布局
    * 选择器必须是以某个前缀开头
      ```css
      .m-detail .info { sRules; }
      .m-detail .current { sRules; }
      .m-detail .news { sRules; }
      ```
    * 前缀说明

        |前缀|说明|示例|
        |:--:|:--|:--|
        |g-|全局通用样式命名，前缀g全称为global，一旦修改将影响全站样式|g-mod|
        |m-|模块命名方式|m-detail|
        |ui-|组件命名方式|ui-selector|
        |js-|所有用于纯交互的命名，不涉及任何样式规则。JSer拥有全部定义权限|js-switch|

    * 出于性能考量，在没有必要的情况下避免元素选择器叠加 Class 和 ID 同时使用。
    * 声明顺序

      1. Positioning（定位）
      2. Box model（盒子模型）
      3. Typographic（排版）
      4. Visual（视觉效果，如动画颜色等）
      5. other（其他）

      ```css
      /* Positioning */
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 100;

      /* Box model */
      display: block;
      box-sizing: border-box;
      width: 100px;
      height: 100px;
      padding: 10px;
      border: 1px solid #e5e5e5;
      border-radius: 3px;
      margin: 10px;
      float: right;
      overflow: hidden;

      /* Typographic */
      font: normal 13px "Helvetica Neue", sans-serif;
      line-height: 1.5;
      text-align: center;

      /* Visual */
      background-color: #f5f5f5;
      color: #fff;
      opacity: 0.8;

      /* Other */
      cursor: pointer;
      ```
### 3.3 TypeScript
 * TypeScript Standard Style  编码风格
    * 尽可能多的使用 ECMAScript 规范
    * 语义化命名
      * **禁用汉语拼音，使用英语**
      * 属性驼峰式命名
      * 方法/函数
        >箭头函数优先。
        > 动词+名词 使用动宾短语和驼峰命名法，参数也使用驼峰命名法，可选参数以 **opt** 开头；如果是私有函数应为 \_+动词+名词； 方法/函数如果是类，应使用名词，且要符合 Pascal 命名法，类的方法/属性和事件使用驼峰命名法。

      * 事件命名
        > on+ 动作状态分词
        ```
        <div onStarted="started()" />
        ```
      * Bool 类型
        > is+名词
        ```
        // 是否前进
        let isGo = true;
        // 是否含有Name
        let hasName = true;
        ```
      * 操作符始终写在前一行，以免分号的隐式插入产生预想不到的问题
        ```
        var y = a ? longButSimpleOperandB : longButSimpleOperandC;
        if (a === "string" || s === "object") {
        }
        ```
    * 缩写规范
          <pre>
            navigation   =>  nav
            header       =>  hd
            description  =>  desc
            button => btn
            previous => prev
          </pre>
      * 应以功能或内容命名，不以表现形式命名；命名-缩写规范使用业界熟知的或者约定俗成的。**常量**采用全部大写，单词间下划线分隔的命名方式。**变量**采用驼峰命名法。**私有属性**、**变量**和**方法**以下划线 \_ 开头。由多个单词组成的 **缩写词**，在命名中，根据当前命名法和出现的位置，所有字母的大小写与首字母的大小写保持一致。**枚举变量** 使用 Pascal 命名法。（与骆驼命名法类似。只不过骆驼命名法是首字母小写，而帕斯卡命名法是首字母大写）
### 3.4 测试
使用Given-When-Then方式测试编写，中间留有空行，测试描述应为“should...when...given...”,测试描述用空格隔开。
```
it("should get 3 when call sum function with parameters 1, 2 ", () => {
    const param1 = 1;
    const param2 = 2;

    const result = sum(param1, param2);

    expect(result).toBe(3);
})
```

**Comment by guzhongren** [comment]
Move to Wiki
